#!/data/data/com.termux/files/usr/bin/bash

# My replacement for cd to most common places.

# ZSH way to point to own file
if [[ -e $funcstack[1] ]]; then
  currentFile="$funcstack[1]"
# Bash way to point to own file
elif [[ -e $BASH_SOURCE ]]; then
  currentFile="$BASH_SOURCE"
fi

base="/data/data/com.termux"

case $1 in
  "") cd - || exit 1 ;;
  pg) 
    if [[ find $base/usr/tmp -type d -name playground.* ]]; then
      cd $(mktemp -d $base/usr/tmp/playground.XXX) || exit 1
    else
      cd /tmp/playground.* || exit 1 
    fi
    ;;
  bo*) vim ~/.vim/VimWiki/VimWiki/Beginner_Boost.md || exit 1 ;;
  con*) cd ~/.config || exit 1 ;;
  loc*) cd ~/.local || exit 1 ;;
  #doc*) cd ~/Documents || exit 1 ;;
  #dow*) cd ~/Downloads || exit 1 ;;
  a*) cd ~/.vim/VimWiki/Argumentation || exit 1;;
  t*) cd ~/.local/termux || exit 1 ;;
  s*) cd ~/.local/termux/scripts || exit 1 ;;
  d*) cd ~/.local/termux/dotfiles || exit 1 ;;
  w*) cd ~/.vim/VimWiki/VimWiki || exit 1 ;;
  z*) cd ~/.vim/VimWiki/Zet || exit 1 ;;
  -h) grep -vE "\-h|sdc1" "${currentFile}" | grep \) | sed -e "s/|.*$//";;
esac

