#!/data/data/com.termux/files/usr/bin/bash

if [[ ! -d ~/.local/termux ]]; then
  mkdir -pv ~/.local
  mv -rf "$(find ~/ -name turmux)" ~/.local/termux
fi

bash "$HOME"/.local/termux/scripts/dotrestore

pkg update

pkg upgrade

pkg install git vim bat zsh fzf gh jq man tmux ncurses-utils openssl-tool ranger eza shellcheck -y

pkg uninstall nano ed -y

pip install termdown

mkdir -pv ~/.local/.zsh

git clone https://github.com/zsh-users/zsh-autosuggestions ~/.local/.zsh/zsh-autosuggestions

git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.local/.zsh/zsh-syntax-highlighting
