#!/data/data/com.termux/files/usr/bin/bash

if [[ $3 ]]; then
  echo "Too many arguments"
elif [[ $2 ]]; then
  cmd=$(command -v "$2")
  case $1 in
    -c) test -n "$cmd" && exec bat -pp "$cmd" ;;
    *) echo "You can use -c <command> to cat the command";
  esac
else
  cmd=$(command -v "$1")
  test -n "$cmd" && exec vim "$cmd"
fi
